services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: checkout
      POSTGRES_PASSWORD: checkout
      POSTGRES_DB: checkout
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
